version: '3.8'
services:
  web:
    build: .
    container_name: dissertation_web
    ports:
      - "8000:8000"
    volumes:
      - ./precomputed_results.csv:/app/precomputed_results.csv
    depends_on:
      - redis
    environment:
       - CELERY_BROKER_URL=redis://redis:6379/0
       - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: dissertation_redis
    ports:
      - "6379:6379"
